name: eagler-actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
      - name: download the eagler server
        run: |
          git clone https://github.com/kingofnetflix/eagler-actions --recursive
          cd eagler-actions
      - name: run the servers
        run: |
          screen -dm bash -c "cd bungee_command; chmod +x run_unix.sh; ./run_unix.sh; exec sh"
          tmux new -d -s bukkit
          sleep 1
          tmux send-keys -t bukkit "cd bukkit_command; chmod +x run_unix.sh; ./run_unix.sh" ENTER
          sleep 1
          tmux capture-pane -pt bukkit
      - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
        with:
         timeout: 1h
         port: 4000
         ngrok_authtoken: 2KHPU9GoTMYKBAxrxATjKziMzjv_5iN4QNLEruRiPx9ZXHQrY
      - name: sleep
        run: sleep 999999999
# kudos to you, lax1dude.
